version: 2
updates:
  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Docker (Root)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Docker (DB)
  - package-ecosystem: "docker"
    directory: "/db"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
