
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - PRIMARY_DATABASE_URL=postgresql://user:password@db:5432/fastapi_template
      - REPLICA_DATABASE_URL=postgresql://user:password@db:5432/fastapi_template
      - TEST_DATABASE_URL=postgresql://user:password@db:5432/fastapi_template_test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_REGION_NAME=us-east-1
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_BUCKET_NAME=my-bucket
      - SECRET_KEY=your_secret_key_here
      - DOMAIN=http://localhost:8000
      - FRONTEND_URL=http://localhost:3000
      - ENV=local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      localstack:
        condition: service_started
    networks:
      - app_network
    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_template
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fastapi_template"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  localstack:
    image: localstack/localstack
    container_name: fastapi_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - ./scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  celery_worker:
    build: .
    container_name: fastapi_celery_worker
    command: celery -A api.core.celery_app worker --loglevel=info
    environment:
      - PRIMARY_DATABASE_URL=postgresql://user:password@db:5432/fastapi_template
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_ACCESS_KEY=test
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - app
      - redis
      - db
    networks:
      - app_network
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: fastapi_celery_beat
    command: celery -A api.core.celery_app beat --loglevel=info
    environment:
      - PRIMARY_DATABASE_URL=postgresql://user:password@db:5432/fastapi_template
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_ACCESS_KEY=test
      - SECRET_KEY=your_secret_key_here
    depends_on:
      - app
      - redis
      - db
    networks:
      - app_network
    volumes:
      - .:/app

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  localstack_data:
