[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = ""
authors = ["Sarthak singh <sarthaksingh2001@gmail.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.120.4"
asyncpg = "^0.30.0"
colorlog = "^6.10.1"
bcrypt = "^5.0.0"
redis = "^7.0.1"
python-jose = "^3.5.0"
pyjwt = "^2.10.1"
orjson = "^3.11.4"
pre-commit = "^4.3.0"
boto3 = "^1.40.64"
celery = "^5.5.3"
asgiref = "^3.10.0"


[tool.poetry.group.dev.dependencies]
mypy = "^1.18.2"
fastapi = { extras = ["standard"], version = "^0.120.4" }
pylint = "^4.0.2"
ruff = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
python_version = "3.12"
plugins = ["pydantic.mypy"]

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true

implicit_optional = true

[[tool.mypy.overrides]]
module = [
  "asyncpg.*",
  "celery.*",
  "boto3.*",
  "botocore.*",
  "jose.*",
  "psutil.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Enable the same rules as flake8, and add isort rules (I)
select = ["E", "F", "W", "I"]
