[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = ""
authors = ["Sarthak singh <sarthaksingh2001@gmail.com>"]
readme = "README.md"
packages = [{ include = "api" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.128.0"
asyncpg = "^0.31.0"
colorlog = "^6.10.1"
bcrypt = "^5.0.0"
redis = "^7.0.1"
python-jose = "^3.5.0"
pyjwt = "^2.11.0"
orjson = "^3.11.7"
pre-commit = "^4.3.0"
boto3 = "^1.42.40"
celery = "^5.6.2"
asgiref = "^3.10.0"
authlib = "^1.6.6"
itsdangerous = "^2.2.0"
pydantic-settings = "^2.12.0"
uvicorn = { extras = ["standard"], version = "^0.40.0" }
pyinstrument = "^5.1.2"
prometheus-fastapi-instrumentator = "^7.1.0"
slowapi = "^0.1.9"
python-json-logger = "^4.0.0"
sentry-sdk = "^2.51.0"
babel = "^2.18.0"
flagsmith = "^5.1.1"
tenacity = "^9.1.2"
werkzeug = "3.1.5"


[tool.poetry.group.dev.dependencies]
mypy = "^1.19.1"
fastapi = { extras = ["standard"], version = "^0.128.0" }
pylint = "^4.0.2"
ruff = "^0.14.14"
pytest = "^9.0.1"
httpx = "^0.28.1"
pytest-asyncio = "^1.3.0"
pytest-cov = "^7.0.0"
isort = "^7.0.0"
bandit = "^1.9.2"
pip-audit = "^2.10.0"
pytest-xdist = "^3.8.0"
httpx-ws = "^0.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.fastapi]
entrypoint = "api.main:app"

[tool.mypy]
python_version = "3.12"
plugins = ["pydantic.mypy"]

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true

implicit_optional = true

[[tool.mypy.overrides]]
module = [
  "asyncpg.*",
  "celery.*",
  "boto3.*",
  "botocore.*",
  "jose.*",
  "psutil.*",
  "uvicorn.*",
  "slowapi.*",
  "pythonjsonlogger.*",
  "secure.*",
  "sentry_sdk.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
# Enable the same rules as flake8, and add isort rules (I)
# Enable the same rules as flake8, and add isort rules (I)
select = ["E", "F", "W", "I"]

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
addopts = "-n auto -v"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
omit = [
  "tests/*",
  "tests/**/*",
  "api/core/feature_flags.py",
  "api/core/i18n.py",
  "api/core/logging_config.py",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
